### ISSUE TITLE
.DS_Store files (MacOS) lead to exception

### ISSUE THREAD

**Issue by jdeschamps** [juglab/DenoiSeg_fiji#2]
The presence of .DS_Store files (MacOS system files) in the image folders lead to the StringLoader being used to load them, and an exception to be thrown when casting the String to Img.

java.lang.ClassCastException: java.lang.String cannot be cast to net.imglib2.img.Img 
at de.csbdresden.denoiseg.train.InputHandler.addTrainingData(InputHandler.java:158) 
at de.csbdresden.denoiseg.command.DenoiSegTrainCommand.train(DenoiSegTrainCommand.java:156) 
at de.csbdresden.denoiseg.command.DenoiSegTrainCommand.run(DenoiSegTrainCommand.java:121) 
at org.scijava.command.CommandModule.run(CommandModule.java:196)
at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java: 624)
at java.lang.Thread.run(Thread.java:748)

**Comment by jdeschamps** [comment]
Fixed [here](https://github.com/jdeschamps/DenoiSeg_fiji/commit/7e19512f22de73da3343705b80d41cd1b5f79992), subject to a pull request soon-ish.
